version: "3.9"
networks: 
  roboshop:
  driver: bridge
services:
  web:
    image: web:v1
    container_name: web
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
  mongo:
    image: mongo:v1
    container_name: mongo
  catalogue:
    image: catalogue:v1
    container_name: catalogue
    depends_on:
    - mongo
  user:
    image: user:v1
    container_name: user
    depends_on:
    - mongo
    - redis